// expo_work/ex03/app/index.tsx
import { Link } from "expo-router"
import { Text, View } from "react-native"



export default function Index(){

    return (
 
        <View style={{marginTop:50}}>

<Text style={{fontSize:50}}>Index</Text>

<Link href="/home" style={{fontSize:30}}>Home</Link>
       
<Link href="/home/aa" style={{fontSize:30}}>AA</Link>

<Link href="(tabs)" style={{fontSize:30}}>tabs</Link>
                </View>
                
    )
}

// vue_work/user-todo-dayjs/src/App.vue
<template>
  <div>
    <h1>dd</h1>

    <router-link to="/Home">home</router-link>
    <br />
    <router-link to="/Month">month</router-link>
    <router-view></router-view>
    <h1>dd</h1>
  </div>
</template>

<script setup>
import { RouterLink, RouterView } from 'vue-router'
</script>

<style lang="scss" scoped></style>
